name: Outputs Demo

on:
  push:

jobs:
  info:
    name: Info
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.get_info.outputs.sha }}
      branch: ${{ steps.get_info.outputs.branch }}
      message: ${{ steps.get_info.outputs.message }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit info
        id: get_info
        run: |
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: info
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Print build info
        run: echo "Building commit ${{ needs.info.outputs.sha }} on branch ${{ needs.info.outputs.branch }}"

  summary:
    name: Summary
    runs-on: ubuntu-latest
    needs: [info, build]
    steps:
      - name: Show summary
        run: |
          echo "### Build Summary"
          echo "Commit SHA: ${{ needs.info.outputs.sha }}"
          echo "Branch: ${{ needs.info.outputs.branch }}"
          echo "Message: ${{ needs.info.outputs.message }}"

